### PR TITLE
Added possibility of displaying timestamp of starting being away state.

### PR DESCRIPTION
**Pull request by bzyx**
It is a nice feature for my friends to see in a simple way at what time I've last time been seen. This feature provides possibility of adding customized time-stamp of last seen time.

Example message: "All Quassel clients vanished from the face of the earth... %%hh:mm:ss%%" which formats to: "All Quassel clients vanished from the face of the earth... 23:20:34"

### CODE REVIEW

**Comment by AlD** [comment]
Closing due to missing responses. Please re-open if needed.

**Comment by digitalcircuit** [comment]
May I take this code and do any finishing work to get it merged?  I'd like to make use of this as the default away message for a shared Quassel core I'm setting up.  I'll give credit in the new pull request of course (*e.g. link to here, preserve first commit*).

**Comment by bzyx** [comment]
@digitalcircuit Hi! Of course I'd be very glad to see that functionality in Quassel. Currently I've no time to work on this, but if you want feel free to grab the code :+1:

**Comment by digitalcircuit** [comment]
@bzyx Pardon the long delay.  I think I've gotten it finished over on [pull request #270](https://github.com/quassel/quassel/pull/270 ).  Thank you very much for the strong starting point!

**Pull request closed without merging**
