### PR TITLE
Allow buffer merge over networks.

### PR DESCRIPTION
**Pull request by kipe**
Allows merging buffers over networks, feature request at http://bugs.quassel-irc.org/issues/1334

> As stated in Issue 83 merge is only possible with chats on the same network.
> As the usage of Bitlbee etc has increased, it would be useful to be able to merge chats across all networks as well. The issue rises as people are now using alternative methods (Facebook, Lync etc) during the day and returning to IRC in the evening.

### CODE REVIEW

**Comment by Zren** [comment]
`message.senderid` is not shared across networks right? Merging buffer's just changed the `message.bufferid` to the new buffer and deletes the old buffer.  Would that cause any problems?

**Comment by kipe** [comment]
`senderid' seems to be shared across networks, as there's only `senderid` and `sender` in the `sender` -table, so that shouldn't cause any problems.

**Comment by Sput42** [comment]
Would be great if you could update the commit message to contain the information from the first comment in its body.

Also please add a "Closes #1334" in the last line, so we can have the issue tracker add a link to this commit and close this issue automatically.

Thanks!

**Comment by kipe** [comment]
Pull request updated as requested.

**Comment by kipe** [comment]
Also, I've been using my fork with this patch for few weeks now and haven't noticed any problems, even though I merge multiple chats over networks daily.

**Comment by Sput42** [comment]
Merged for 0.12.0, thanks!

**Pull request closed without merging**
