### PR TITLE
Nobrackets

### PR DESCRIPTION
**Pull request by AlD**
Removes brackets around sender names.

### CODE REVIEW

**Comment by benapetr** [comment]
Yes, old school users need brackets. Don't merge this unless it's optional please.

**Comment by digitalcircuit** [comment]
If needed, I'm willing to try taking on the work needed to implement a new option to control this.  Quasseldroid alpha has a simple toggle which seems like it'd satisfy both camps.

**Comment by AlD** [comment]
By all means, go for it.

**Comment by AlD** [comment]
Superseded by #185.

**Pull request closed without merging**
