### PR TITLE
fix wrong zh_CN translation in quassel.notifyrc

### PR DESCRIPTION
**Pull request by zhsj**

### CODE REVIEW

**Comment by AlD** [comment]
Thanks for your contribution!

Quassel's translations are maintained in Transifex (https://www.transifex.com/ald/quassel/). Could you please submit your fix there?

**Comment by zhsj** [comment]
I create this PR since quassel.notifyrc is not on transifex.

**Comment by zhsj** [comment]
So, what is going on? 
Will you upload `quassel.notifyrc` file to transifex or reopen this PR?

**Comment by AlD** [comment]
Ah, fair point. I didn't realize those hadn't made it to Transifex yet.
Yes, I'll look into adding the .desktop and .notifyrc files into the normal transifex workflow.
For now, I'll merge this PR. Thanks!

**Comment by AlD** [comment]
Merged, thanks!

**Pull request closed without merging**
