### PR TITLE
Fix missing joins, speed up login, other IRCv3 fixes

### PR DESCRIPTION
**Pull request by digitalcircuit**
## In short
* Handle non-compliant ```extended-join``` messages as normal joins
 * Fixes missing joins on some networks (*e.g. during hostname changes*)
* Update ```processIrcEventJoin``` to use ```extended-join``` account name information
 * This was accidentally left out of [the IRCv3 fix-up pull request](https://github.com/quassel/quassel/pull/198 )
* Improve some commands to handle missing parameters better
* Improve capability handling
 * Allow for capabilities with multiple value pairs, e.g. ```sts=duration=31536000,port=6697```
 * Sort capabilities before requesting for consistency among networks
 * Handle IRCv3-compliant servers that don't offer any capabilities (see [IRCv3 pull request #264](https://github.com/ircv3/ircv3-specifications/pull/264))
 * Try to recover from bad replies to ```CAP ACK``` and ```CAP NAK```
 * Optimize ```Network::clearCaps``` to only issue a ```SYNC``` when capabilities removed
* Request multiple capabilities at once
 * Always handle special cases (*e.g. SASL*) individually
 * If batch fails, retry capabilities one at a time (*limitation of spec*)
 * Speeds up login, fixes some connection timeouts during login

Criteria | Rank | Reason
---------|---------|-------------
Impact | ★★★ *3/3* | Fixes missing joins on some servers, timeouts, general IRCv3 robustness
Risk | ★★☆ *2/3* | Might allow faulty parsing or break capability negotiation
Intrusiveness | ★☆☆ *1/3* | Minor changes, shouldn't interfere with non-IRCv3 pull requests

*Thanks to @Polsaker for finding the ```extended-join``` issue, and thanks to @justJanne and @genius3000 for finding the connection timeout issue!*

## Example
When Quassel receives a join that doesn't match ```extended-join``` parameters, it's handled as a normal ```join``` instead, logging this warning:
```
2016-06-29 00:11:51 Debug: extended-join requires 3 params, got: ("#achannelyoujoined") , handling as a regular join
```
Debug logging isn't enabled by default for the Quassel core, so usually this message will be hidden.

## Verification
To easily test these changes without relying on a non-compliant server, put the following code [in line 93 of ```ircparser.cpp```](https://github.com/quassel/quassel/blob/5b164bbc62960cea62a31287f679197b623ad7ac/src/core/ircparser.cpp#L93 ), then on an ```extended-join``` capable server (*e.g. Bitlbee*) receive messages with the magic phrases.  If all is working, the ```BAD``` phrases should still have the intended effect (*joining channel, clearing away, etc*).

```cpp
if (msg.contains("MAGIC_BAD_JOIN")) {
    qDebug() << "MAGIC_BAD_JOIN test";
    msg = ":TestNick!user@host JOIN #achannelyoujoined";
} else if (msg.contains("MAGIC_GOOD_JOIN")) {
    qDebug() << "MAGIC_GOOD_JOIN test";
    msg = ":TestNickGood!user@host JOIN #achannelyoujoined Account :Real Name!";
} else if (msg.contains("MAGIC_SET_AWAY")) {
    qDebug() << "MAGIC_SET_AWAY test";
    msg = ":TestNick!user@host AWAY :I'm not here!";
} else if (msg.contains("MAGIC_BAD_AWAY")) {
    qDebug() << "MAGIC_BAD_AWAY test";
    msg = ":TestNick!user@host AWAY";
} else if (msg.contains("MAGIC_BAD_WHOAUTH")) {
    qDebug() << "MAGIC_BAD_WHOAUTH test";
    msg = ":localhost 330 TestNick TestNick TestNickAcct";
} else if (msg.contains("MAGIC_BAD_NOCHAN")) {
    qDebug() << "MAGIC_BAD_NOCHAN test";
    msg = ":localhost 403 yournick #achannelyoujoined";
}
```

*Testing code is not included inside the commit.*

### CODE REVIEW

**Comment by Nevcairiel** [comment]
Personally I would like smaller commits instead "other random fixes" bunched together into the first one. It helps to see which changes handle which issues, without having to read all the context of the patch first.

Feel free to ignore, ultimately Sput has to review this. ;) But it is a good guideline for any future development, distinct changes get distinct commits.

**Comment by digitalcircuit** [comment]
I agree, and I've split up the previous two commits into five distinct, independent commits.  It's always easier to squash commits if needed during code review than to try to split them apart, and as discussed on IRC, keeping them separate will help with troubleshooting in the future.

Thanks for catching my mistake!

**Comment by digitalcircuit** [comment]
Updated pull request to fix connection timeouts.  I forgot to carry over the call to ```coreNet->addCap()``` when modifying capability negotiation.

Also fixed handling of servers without any capabilities, and improved handling of servers that send bad replies to ```CAP ACK``` or ```CAP NAK```.

Thanks to @Polsaker and @romibi for finding the ```addCap``` issue!

**Comment by digitalcircuit** [comment]
I've added batch requesting of capabilities to improve login performance and hopefully fix some timeout issues during negotiation.

Apologies for the somewhat unfocused nature of this pull request.  All of these fixes modify the same section of code in tightly-knit ways, which would make separate pull requests difficult.

**Pull request closed without merging**
