### PR TITLE
Some changes for OSX

### PR DESCRIPTION
**Pull request by stonerl**
Since icons are uncommon in the Global Menu and usually in the context-menus as well, they won't be shown on OSX. Also the the "Show Menubar" Button has no use on OSX and has therefor been removed.

Furthermore a small workaround. The the inputwidget does not resize in OSX with a font smaller 14pt. So a hint was added to the settingspage and by default the font will be set to 14.

### CODE REVIEW

**Comment by Deph0** [comment]
You forgot right click toggle for menubar, and could you elaborate on what you mean with the input widget? it resizes just fine with fontsize 9 for me.

-Deas

**Comment by stonerl** [comment]
Since I removed it from the Global menu it also is not available from the right click menu. The problem with the inputwidget is quite simple. It only resizes when I use a font with 14pt or bigger. If I use a smaller font then it only creates multiple lines but it does not resize the input field according to the numbers of max-lines I have set.

**Comment by Deph0** [comment]
Another idea could be to implement the "minimized" function to closeing the window so quassel doesn't quit because you hit X (this feature already exists inside the tray icon).

For example, in Skype, you have to right-click the dock icon to quit skype, if you hit X, you close the window but not the instance, and you can hit cmd+1 to close the window(not the instance) as well.

**Comment by AlD** [comment]
The commits in this PR seem to address different unrelated issues.
Please submit them in individual PRs and if you could add screenshots to describe the UI changes that would help reviewing a lot. Thanks!

**Pull request closed without merging**
