### PR TITLE
Shell script to delete users from SQlite database

### PR DESCRIPTION
**Pull request by sir-ragna**
Is this welcome in the main repo? Or is this more something to put on the wiki or in documentation somewhere?

### CODE REVIEW

**Comment by jonasbits** [comment]
Tested and works fine! Thanks

**Comment by digitalcircuit** [comment]
Ideally the `quasselcore` command would have a `--del-user` flag or the like, but that gets complicated since if the core is running, things will go boom.  It would allow using it on Windows, too.

It could fit on the [wiki's SQLite page](http://bugs.quassel-irc.org/projects/quassel-irc/wiki/SQLite ), perhaps with a separate page for the full script, even if the project maintainers don't want this in the main repo.

**Comment by SvetlanaTkachenko** [comment]
@sir-ragna I would like to add this script to the wiki since I do not already see it there. There are two questions.

1. What license are you releasing this file with? Quassel is released under GNU General Public License "either version 2 of the License, or (at your option) version 3". However you are free to choose your own licence. It is common to specify GNU GPL version 3 "or later".
2. From my personal perspective, naming the script 'usermanagement' may be confusing. People may run 'usermanagement sirragna' and may expect it to present options (change password, disable, delete, enable this user) but it deletes straight away. Perhaps the script needs to be renamed to 'quasseldeleteuser.sh'?

**Comment by sir-ragna** [comment]
@SvetlanaTkachenko  Sorry for the late reply.

1. Consider it multi-licensed under 3-Clause BSD License, GPLv2 and GPLv3. Choose whatever you like.
2. Rename it in any way you see fit.

Do with it as you wish.

**Comment by SvetlanaTkachenko** [comment]
@sir-ragna Thank you. Please add author header and licence header into the file, so that the script users have the licensing information readily available without needing to locate to this discussion.

**Comment by sir-ragna** [comment]
@SvetlanaTkachenko I added an author statement and appended the license statements.

I'm personally not a fan of putting all the license information in the header. That is why I added the boilerplate at the end of the file. Feel free of course to change it however you like.

**Comment by sir-ragna** [comment]
I finally made a wiki account and put the script [there](https://bugs.quassel-irc.org/projects/quassel-irc/wiki/Delete_Users). Just like @digitalcircuit suggested.

**Pull request closed without merging**
