### PR TITLE
Enable Link-Preview on appveyor builds

### PR DESCRIPTION
**Pull request by romibi**
Pros:
- Those who want it don't have to build quassel themselves anymore

Cons (what I heard):
- Adds about 23MB to the Download
- Whole Link Preview should be redone anyways

Comments:
- Those who don't want it or have problems with it can disable it in the Chat View Settings
- I don't think the Cons are a problem for this

### CODE REVIEW

**Comment by TheOneRing** [comment]
You need to ship icu too with webkit.

**Comment by romibi** [comment]
they were already in it … but some others were missing

**Comment by TheOneRing** [comment]
Seems to work :+1: :smiley:

**Comment by AlD** [comment]
Thanks for the patch, romibi, and thanks for testing, TheOneRing!

**Pull request merged**
