### PR TITLE
Pass -dead_strip and -dead_strip_dylibs on macOS

### PR DESCRIPTION
**Pull request by rex4539**
From `man ld`.
```
-dead_strip
                 Remove functions and data that are unreachable by the entry point or exported symbols.
```

Before:
Screen Shot 2020-01-12 at 19 52 30
After:
Screen Shot 2020-01-12 at 20 08 08

From `man ld`.
```
-dead_strip_dylibs
                 Remove dylibs that are unreachable by the entry point or exported symbols. That is, suppresses the generation of load
                 command commands for dylibs which supplied no symbols during the link. This option should not be used when linking
                 against a dylib which is required at runtime for some indirect reason such as the dylib has an important initializer.
```

Before:
```
% otool -L quassel
        /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 162.0.0)
	@rpath/libquassel-core.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-qtui.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	/opt/local/libexec/qt5/lib/QtSql.framework/Versions/5/QtSql (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/libexec/qt5/lib/libqca-qt5.2.dylib (compatibility version 2.0.0, current version 2.2.1)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 59306.41.2)
	@rpath/libquassel-uisupport.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-client.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-common.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1069.11.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1673.126.0)
	/opt/local/libexec/qt5/lib/QtNetwork.framework/Versions/5/QtNetwork (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/libexec/qt5/lib/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/libexec/qt5/lib/QtGui.framework/Versions/5/QtGui (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/libexec/qt5/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.14.0, current version 5.14.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
```
After:
```
% otool -L quassel
        @rpath/libquassel-core.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-qtui.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-client.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-common.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	/opt/local/libexec/qt5/lib/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/libexec/qt5/lib/QtGui.framework/Versions/5/QtGui (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/libexec/qt5/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.14.0, current version 5.14.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
```

Before:
```
% otool -L Quassel.app/Contents/MacOS/Quassel
        /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 162.0.0)
	@rpath/libquassel-core.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-qtui.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	/opt/local/libexec/qt5/lib/QtSql.framework/Versions/5/QtSql (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/libexec/qt5/lib/libqca-qt5.2.dylib (compatibility version 2.0.0, current version 2.2.1)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 59306.41.2)
	@rpath/libquassel-uisupport.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-client.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-common.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1069.11.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1673.126.0)
	/opt/local/libexec/qt5/lib/QtNetwork.framework/Versions/5/QtNetwork (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/libexec/qt5/lib/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/libexec/qt5/lib/QtGui.framework/Versions/5/QtGui (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/libexec/qt5/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.14.0, current version 5.14.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
```
After:
```
% otool -L Quassel.app/Contents/MacOS/Quassel
        @rpath/libquassel-core.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-qtui.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-client.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-common.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	/opt/local/libexec/qt5/lib/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/libexec/qt5/lib/QtGui.framework/Versions/5/QtGui (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/libexec/qt5/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.14.0, current version 5.14.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
```

Before:
```
% otool -L Quassel\ Client.app/Contents/MacOS/Quassel\ Client
        /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 162.0.0)
	@rpath/libquassel-qtui.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-uisupport.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-client.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-common.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1069.11.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1673.126.0)
	/opt/local/libexec/qt5/lib/QtNetwork.framework/Versions/5/QtNetwork (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/libexec/qt5/lib/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/libexec/qt5/lib/QtGui.framework/Versions/5/QtGui (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/libexec/qt5/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.14.0, current version 5.14.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
```
After:
```
% otool -L Quassel\ Client.app/Contents/MacOS/Quassel\ Client
        @rpath/libquassel-qtui.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-common.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	/opt/local/libexec/qt5/lib/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/libexec/qt5/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.14.0, current version 5.14.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
```

Before:
```
% otool -L quasselclient
        /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 162.0.0)
	@rpath/libquassel-qtui.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-uisupport.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-client.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-common.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1069.11.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1673.126.0)
	/opt/local/libexec/qt5/lib/QtNetwork.framework/Versions/5/QtNetwork (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/libexec/qt5/lib/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/libexec/qt5/lib/QtGui.framework/Versions/5/QtGui (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/libexec/qt5/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.14.0, current version 5.14.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
```
After:
```
% otool -L quasselclient
        @rpath/libquassel-qtui.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-common.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	/opt/local/libexec/qt5/lib/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/libexec/qt5/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.14.0, current version 5.14.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
```

Before:
```
% otool -L quasselcore
        /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 162.0.0)
	@rpath/libquassel-core.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	/opt/local/libexec/qt5/lib/QtSql.framework/Versions/5/QtSql (compatibility version 5.14.0, current version 5.14.0)
	@rpath/libquassel-common.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	/opt/local/libexec/qt5/lib/QtNetwork.framework/Versions/5/QtNetwork (compatibility version 5.14.0, current version 5.14.0)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1069.11.0)
	/opt/local/libexec/qt5/lib/libqca-qt5.2.dylib (compatibility version 2.0.0, current version 2.2.1)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1673.126.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 59306.41.2)
	/opt/local/libexec/qt5/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.14.0, current version 5.14.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
```
After:
```
% otool -L quasselcore
        @rpath/libquassel-core.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	@rpath/libquassel-common.0.13.50.dylib (compatibility version 0.0.0, current version 0.13.50)
	/opt/local/libexec/qt5/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.14.0, current version 5.14.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
```

### CODE REVIEW

**Comment by justjanne** [comment]
The `-dead_strip_dylib` option has suspicious results, especially QtSql and QtNetwork being stripped seems like a really bad thing (as they're required for some of the most basic functionality).

**Comment by rex4539** [comment]
Please keep in mind that this affects only macOS.

If you are on macOS, give it a try and let me know. Everything appears to be working fine here but some additional testing would be appreciated :)

**Comment by rex4539** [comment]
Added another commit that is complimentary and will help.

From `man ld`.
```
-bind_at_load
                 Sets a bit in the mach header of the resulting binary which tells dyld to bind all symbols when the binary is loaded,
                 rather than lazily.
```

**Comment by rex4539** [comment]
Withdrawing due to no interest.

**Pull request closed without merging**
