### PR TITLE
[WIP] Travis NG

### PR DESCRIPTION
**Pull request by Sput42**
Try to get docker-based build working in Travis.

### CODE REVIEW

**Comment by Sput42** [comment]
To be clear to people stumbling over this: This will go in post-0.13, as part of the build system cleanup and build requirement bump.

**Comment by digitalcircuit** [comment]
I'm guessing removing AppVeyor configuration is just to stop automated builds from filling up the CI queue?  If so, just a reminder to put it back post-0.13 before merging this :slightly_smiling_face:

**Comment by Sput42** [comment]
Yes, AppVeyor is temporarily removed just so we don't block its queue while playing around with this.

**Comment by Sput42** [comment]
Superseded by #402.

**Pull request closed without merging**
