### PR TITLE
Add spell-checking support via the Sonnet framework

### PR DESCRIPTION
**Pull request by sandsmark**
I rebased your patch and stuff

### CODE REVIEW

**Comment by avih** [comment]
ping...

**Comment by avih** [comment]
Should this be working out of the box now on Windows? it seems that the appveyor builds don't include `KF5Sonnet` as far as I can tell (as far as @romibi can tell, actually) and I'm also not seeing any speller option at the input widget config.

**Comment by sandsmark** [comment]
yeah, appveyor needs to be updated. I'm not familiar with it, but it looks like it should be very straightforward, just copying most of the config for e. g. snorenotify and replacing "snorenotify" with "sonnet" (they're both on quickgit.kde.org, for example).

**Comment by avih** [comment]
How would dictionaries be handled (once it works)? Should they be downloaded manually (where from?) and place them at the quassel dir?

**Pull request merged**
