### PR TITLE
set GIT_HEAD and GIT_DESCRIBE from environment

### PR DESCRIPTION
**Pull request by agaida**
some additional cmake magic, make sense in a build chroot where the upstream repo is not available - i don't want to build git snapshots local - but i would like to have the information, what is build in the about box

### CODE REVIEW

**Comment by Sput42** [comment]
Not sure what you want to do with this. Would you give those variables directly to CMake (-DENV_GIT_HEAD=whatever)? Because I don't see you reading it from an environment variable...

**Comment by agaida** [comment]
absolutely right - i don't have git repos in my build chroot (and i don't want to have to be true) - so i create the files at the time i do the checkout/clone from repo 

<pre>
GIT_HEAD=$(shell [ -f debian/git_head ] && cat debian/git_head)
GIT_DESCRIBE=$(shell [ -f debian/git_describe ] && cat debian/git_describe)
</pre>

and later in debian/rules

<pre>
override_dh_auto_configure:
        dh_auto_configure -- \
            -DUSE_QT5=ON \
            ...
            -DENV_GIT_HEAD=$(GIT_HEAD) \
            -DENV_GIT_DESCRIBE=$(GIT_DESCRIBE)
</pre>

it is the least invasive way to provide these informations - as we build often and not only releases in siduction i think it is useful to have the commit on which the package is based on

**Comment by Sput42** [comment]
Hmm, I would change the names then, because the ENV_* is confusing (as we're not actually reading from the environment). But I'd have to think about something better...

**Comment by agaida** [comment]
-DBUILD_GIT_$foo or
-DSCRCIPT_GIT_$foo or
-DDIRECT_GIT_$foo or
-DGIVEN_GIT_$foo 
only brainstorming

**Pull request merged**
