### PR TITLE
Nick flair prefix

### PR DESCRIPTION
**Pull request by esainane**
This builds upon #141.

 - This uses flairs from the PREFIX capability reported by the server
 - This is configurable from the chat view settings, and is disabled by default

### CODE REVIEW

**Comment by justjanne** [comment]
Code duplication:

A large part of your code duplicates https://github.com/quassel/quassel/blob/master/src/common/network.cpp#L141-L147

**Comment by AlD** [comment]
Sorry, haven't reviewed the code, but please respond to the previous comment if you care about this PR.

**Comment by RoboMWM** [comment]
Would be appreciated if this feature (which I'd imagine is a "standard" for most clients) could be added.

**Comment by justjanne** [comment]
@AlD : You might want to reopen, and then use the reviewer-feature to block the merge – if the request is closed, it might end up being forgotten about.

**Comment by esainane** [comment]
This should not currently be considered mergeable. There is a lot more to do in order to achieve this properly, and most of that comes under the daunting task of implementing backwards-compatible serialization.

**Pull request closed without merging**
